# Generated by Django 4.2.1 on 2023-06-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('organisation', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='', max_length=150)),
                ('postal_code', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=150)),
                ('message', models.TextField(default='')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
