version: '3.8'


services:
  web:
    build: ./app
    command: gunicorn j2lprintable.wsgi:application --bind 0.0.0.0:8000 --noreload
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web


volumes:
  static_volume:
  media_volume: