# Generated by Django 4.2.1 on 2023-06-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_test_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
